# Generated by Django 5.2.3 on 2025-09-14 12:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_roadmap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonpart",
            name="description",
        ),
        migrations.AddField(
            model_name="lessonpart",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
