# Generated by Django 5.2.3 on 2025-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_rename_description_to_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonpart",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("theory", "Theory"),
                    ("test", "Test"),
                    ("assignment", "Assignment"),
                ],
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
