# Generated by Django 5.2.3 on 2025-09-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_alter_lessonpart_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchingpair",
            name="matching_question",
        ),
        migrations.AddField(
            model_name="matchingpair",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matching_pairs",
                to="course.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Special instructions for matching questions or other question types",
                null=True,
                verbose_name="Instructions",
            ),
        ),
        migrations.DeleteModel(
            name="MatchingQuestion",
        ),
    ]
