# Generated by Django 5.2.3 on 2025-09-14 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_remove_matchingpair_matching_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="points",
        ),
    ]
