# Generated by Django 5.2.3 on 2025-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_remove_question_points_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Correct Answer"
            ),
        ),
    ]
