# Generated by Django 5.2.3 on 2025-09-14 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_add_correct_answer_to_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrueFalseQuestion",
        ),
    ]
