# Generated by Django 5.2.3 on 2025-09-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_remove_true_false_question_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="expected_answer",
            field=models.TextField(
                blank=True,
                help_text="Expected answer for reference (optional)",
                null=True,
                verbose_name="Expected Answer",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Question Number"
            ),
        ),
        migrations.DeleteModel(
            name="BookTestQuestion",
        ),
    ]
