# Generated by Django 5.2.3 on 2025-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_question_expected_answer_question_question_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="expected_answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_number",
        ),
        migrations.AddField(
            model_name="question",
            name="book_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of book test questions with their answers",
                null=True,
                verbose_name="Book Questions",
            ),
        ),
    ]
