# Generated by Django 5.2.3 on 2025-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_remove_question_expected_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="book_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of book test questions with their answers. Example: [{'expected_answer': 'A', 'question_number': 1}]",
                null=True,
                verbose_name="Book Questions",
            ),
        ),
    ]
