# Generated by Django 5.2.3 on 2025-09-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0011_add_book_questions_field"),
    ]

    operations = [
        # First, add new fields to Question model
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="questions/images/",
                verbose_name="Question Image",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="regular_question_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("text_choice", "Text Choice"),
                    ("image_choice", "Image Choice"),
                    ("video_choice", "Video Choice"),
                ],
                default="text_choice",
                max_length=50,
                null=True,
                verbose_name="Regular Question Type",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Video URL"),
        ),
        # Then, add the new question field to AnswerChoice
        migrations.AddField(
            model_name="answerchoice",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="course.question",
            ),
        ),
        # Now we can safely update the unique_together constraint
        migrations.AlterUniqueTogether(
            name="answerchoice",
            unique_together={("question", "choice_label")},
        ),
        # Finally, remove old field and model
        migrations.RemoveField(
            model_name="answerchoice",
            name="regular_question",
        ),
        migrations.DeleteModel(
            name="RegularTestQuestion",
        ),
    ]
