# Generated by Django 5.2.3 on 2025-09-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0012_migrate_to_simplified_question_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Progress percentage from 0.00 to 100.00",
                        max_digits=5,
                        verbose_name="Progress Percentage",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "finish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finish Date"
                    ),
                ),
                (
                    "coins_earned",
                    models.IntegerField(default=0, verbose_name="Coins Earned"),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Points Earned"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="Last Accessed"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_courses",
                        to="course.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Course",
                "verbose_name_plural": "User Courses",
                "ordering": ["-last_accessed"],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="UserLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Progress Percentage",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_lessons",
                        to="course.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_lessons",
                        to="course.usercourse",
                        verbose_name="User Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Lesson",
                "verbose_name_plural": "User Lessons",
                "ordering": ["lesson__id"],
                "unique_together": {("user_course", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="UserTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "finish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finish Date"
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="Is Passed"),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="Total Questions"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="Correct Answers"),
                ),
                (
                    "attempt_number",
                    models.IntegerField(default=1, verbose_name="Attempt Number"),
                ),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="Is Submitted"),
                ),
                (
                    "is_in_progress",
                    models.BooleanField(default=True, verbose_name="Is In Progress"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to="course.test",
                        verbose_name="Test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Test",
                "verbose_name_plural": "User Tests",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserLessonPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "lesson_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_lesson_parts",
                        to="course.lessonpart",
                        verbose_name="Lesson Part",
                    ),
                ),
                (
                    "user_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_lesson_parts",
                        to="course.userlesson",
                        verbose_name="User Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Lesson Part",
                "verbose_name_plural": "User Lesson Parts",
                "ordering": ["lesson_part__order"],
                "unique_together": {("user_lesson", "lesson_part")},
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "boolean_answer",
                    models.BooleanField(
                        blank=True,
                        help_text="For true/false questions",
                        null=True,
                        verbose_name="Boolean Answer",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="For open-ended questions",
                        null=True,
                        verbose_name="Text Answer",
                    ),
                ),
                (
                    "matching_answer",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object storing matching pairs for matching questions",
                        null=True,
                        verbose_name="Matching Answer",
                    ),
                ),
                (
                    "book_answer",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of answers for book test questions",
                        null=True,
                        verbose_name="Book Answer",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is Correct"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Answered At"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="course.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        help_text="For multiple choice questions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.answerchoice",
                        verbose_name="Selected Choice",
                    ),
                ),
                (
                    "user_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="course.usertest",
                        verbose_name="User Test",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Answer",
                "verbose_name_plural": "User Answers",
                "ordering": ["question__order"],
                "unique_together": {("user_test", "question")},
            },
        ),
    ]
