# Generated by Django 5.2.3 on 2025-09-16 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0013_usercourse_userlesson_usertest_userlessonpart_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercourse",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "User Course",
                "verbose_name_plural": "User Courses",
            },
        ),
        migrations.RemoveField(
            model_name="usercourse",
            name="last_accessed",
        ),
    ]
