# Generated by Django 5.2.3 on 2025-09-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0014_alter_usercourse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="Is Expired"),
        ),
    ]
