# Generated by Django 5.2.3 on 2025-09-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0015_usercourse_is_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmaps",
                to="course.subject",
            ),
        ),
    ]
