# Generated by Django 5.2.3 on 2025-09-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0016_roadmap_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="attached_files",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="course.file"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="book_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of book test questions with their answers. Example: [{'questions_count': 10, 'questions': [{'expected_answer': 'A', 'question_number': 1}, {'expected_answer': 'B', 'question_number': 2}]}]",
                null=True,
                verbose_name="Book Questions",
            ),
        ),
    ]
