# Generated by Django 5.2.3 on 2025-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0017_question_attached_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="attached_files",
        ),
        migrations.AddField(
            model_name="test",
            name="attached_files",
            field=models.ManyToManyField(
                blank=True, related_name="tests", to="course.file"
            ),
        ),
    ]
