# Generated by Django 5.2.3 on 2025-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_question_attached_files_test_attached_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_count',
            field=models.IntegerField(default=10, help_text='Number of random questions to show to user', verbose_name='Questions Count'),
        ),
    ]
