# Generated by Django 5.2.3 on 2025-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_test_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Answered At'),
        ),
    ]
