# Generated by Django 5.2.3 on 2025-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0020_alter_useranswer_answered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
