# Generated by Django 5.2.3 on 2025-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0021_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_can_pay_with_coin",
            field=models.BooleanField(
                default=False, verbose_name="Is Can Pay With Coin"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_can_pay_with_referral",
            field=models.BooleanField(
                default=False, verbose_name="Is Can Pay With Referral"
            ),
        ),
    ]
