# Generated by Django 5.2.3 on 2025-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0022_course_is_can_pay_with_coin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration_months",
            field=models.IntegerField(default=0, verbose_name="Duration Months"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="practical_pass_ball",
            field=models.IntegerField(default=0, verbose_name="Practical Pass Ball"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="theoretical_pass_ball",
            field=models.IntegerField(default=0, verbose_name="Theoretical Pass Ball"),
        ),
    ]
