# Generated by Django 5.2.3 on 2025-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_course_duration_months_lesson_practical_pass_ball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
    ]
