# Generated by Django 5.2.3 on 2025-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0024_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video_preview",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/videos/",
                verbose_name="Video Preview",
            ),
        ),
    ]
