# Generated by Django 5.2.3 on 2025-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0025_course_video_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="video_preview",
            field=models.URLField(blank=True, null=True, verbose_name="Video Preview"),
        ),
    ]
