# Generated by Django 5.2.3 on 2025-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0026_change_video_preview_to_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonpart",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lessonpart",
            name="hls_processing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                null=True,
                verbose_name="HLS Processing Status",
            ),
        ),
        migrations.AddField(
            model_name="lessonpart",
            name="hls_video_url",
            field=models.URLField(
                blank=True, editable=False, null=True, verbose_name="HLS Video URL"
            ),
        ),
        migrations.AddField(
            model_name="lessonpart",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="lesson_videos/", verbose_name="Video"
            ),
        ),
    ]
