# Generated by Django 5.2.3 on 2025-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0027_remove_lessonpart_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="is_free_trial",
            field=models.BooleanField(
                default=False,
                help_text="True if user is accessing free lessons without payment",
                verbose_name="Is Free Trial",
            ),
        ),
    ]
