# Generated by Django 5.2.3 on 2025-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0028_add_is_free_trial_to_user_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonpart",
            name="awards_given",
            field=models.BooleanField(
                default=False,
                help_text="True if coins/points were awarded for completing this part",
                verbose_name="Awards Given",
            ),
        ),
    ]
