# Generated by Django 5.2.3 on 2025-11-19 20:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0029_userlessonpart_awards_given"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerchoice",
            name="choice_text",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Choice Text"
            ),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="left_item",
            field=tinymce.models.HTMLField(verbose_name="Left Item"),
        ),
        migrations.AlterField(
            model_name="matchingpair",
            name="right_item",
            field=tinymce.models.HTMLField(verbose_name="Right Item"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=tinymce.models.HTMLField(verbose_name="Question text"),
        ),
    ]
