from .CourseList.views import *  # noqa
from .LessonPartDetail.views import *  # noqa
from .LessonPartList.views import *  # noqa
from .LessonsList.views import *  # noqa
from .Roadmap.views import *  # noqa
from .SubjectList.views import *  # noqa
from .TestDetail.views import *  # noqa
from .UserCoursesList.views import *  # noqa
from .UserLessonCreate.views import *  # noqa
