# Generated by Django 5.2.3 on 2025-11-19 20:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_region_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usefullink",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Description"),
        ),
    ]
