# Generated by Django 5.2.3 on 2025-09-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_region_district"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_index",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address index"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=255,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Grade"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.region",
                verbose_name="Region",
            ),
        ),
    ]
