# Generated by Django 5.2.3 on 2025-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_address_index_user_birth_date_user_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("TEACHER", "Teacher")],
                db_index=True,
                default="STUDENT",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
