# Generated by Django 5.2.3 on 2025-10-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coin",
            field=models.PositiveIntegerField(
                default=0, help_text="User's coin balance", verbose_name="Coin"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.PositiveIntegerField(
                default=0, help_text="User's point balance", verbose_name="Point"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="The teacher assigned to this student",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
    ]
