# Generated by Django 5.2.3 on 2025-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_coin_user_point_user_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_point",
            field=models.PositiveIntegerField(
                default=0,
                help_text="User's referral point balance",
                verbose_name="Referral point",
            ),
        ),
    ]
