# Generated by Django 5.2.3 on 2025-10-22 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0022_course_is_can_pay_with_coin_and_more"),
        ("users", "0006_user_teacher_global_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="teacher_global_limit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="teacher_global_limit_used",
        ),
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_groups",
                to="course.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="current_member_count",
            field=models.IntegerField(default=0, verbose_name="Current member count"),
        ),
        migrations.AddField(
            model_name="group",
            name="max_member_count",
            field=models.IntegerField(default=0, verbose_name="Max member count"),
        ),
        migrations.CreateModel(
            name="TeacherGlobalLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "limit",
                    models.IntegerField(
                        default=0,
                        help_text="Teacher's global limit",
                        verbose_name="Limit",
                    ),
                ),
                (
                    "used",
                    models.IntegerField(
                        default=0,
                        help_text="Teacher's global limit used",
                        verbose_name="Used",
                    ),
                ),
                (
                    "remaining",
                    models.IntegerField(
                        default=0,
                        help_text="Teacher's global limit remaining",
                        verbose_name="Remaining",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_teacher_global_limits",
                        to="course.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_global_limits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher global limit",
                "verbose_name_plural": "Teacher global limits",
            },
        ),
    ]
