# Generated by Django 5.2.3 on 2025-10-24 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_user_teacher_global_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="current_member_count",
        ),
        migrations.RemoveField(
            model_name="group",
            name="max_member_count",
        ),
    ]
