# Generated by Django 5.2.3 on 2025-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_group_current_member_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="current_member_count",
            field=models.IntegerField(default=0, verbose_name="Current member count"),
        ),
        migrations.AddField(
            model_name="group",
            name="group_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Group end date"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="group",
            name="max_member_count",
            field=models.IntegerField(default=0, verbose_name="Max member count"),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
