# Generated by Django 5.2.3 on 2025-10-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0023_course_duration_months_lesson_practical_pass_ball_and_more"),
        ("users", "0009_group_current_member_count_group_group_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMemberGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "theoretical_ball",
                    models.IntegerField(default=0, verbose_name="Theoretical ball"),
                ),
                (
                    "practical_ball",
                    models.IntegerField(default=0, verbose_name="Practical ball"),
                ),
                (
                    "group_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_member_grades",
                        to="users.groupmember",
                        verbose_name="Group member",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_group_member_grades",
                        to="course.lesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group member grade",
                "verbose_name_plural": "Group member grades",
            },
        ),
    ]
