# Generated by Django 5.2.3 on 2025-12-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_kmteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmteacher',
            options={'verbose_name': 'KM Teacher', 'verbose_name_plural': 'KM Teachers'},
        ),
    ]
