# Generated by Django 5.2.3 on 2025-12-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_kmteacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmteacher',
            name='is_repetitor',
            field=models.BooleanField(default=False),
        ),
    ]
