# Generated by Django 5.2.3 on 2025-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_kmteacher_is_repetitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmteacher',
            name='teacher_type',
            field=models.CharField(choices=[('CHEMISTRY', 'Kimyo'), ('BIOLOGY', 'Biologiya')], default='CHEMISTRY', max_length=20),
        ),
    ]
