# Generated by Django 5.2.3 on 2025-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="duration",
            field=models.IntegerField(null=True, verbose_name="duration in month"),
        ),
    ]
