# Generated by Django 5.2.3 on 2025-10-06 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0022_course_is_can_pay_with_coin_and_more"),
        ("payment", "0002_transaction_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="coins_used",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of coins used in this transaction",
                null=True,
                verbose_name="coins used",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original course price before discounts",
                max_digits=12,
                null=True,
                verbose_name="original amount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="promo_code",
            field=models.CharField(
                blank=True,
                help_text="Promo code used in this transaction",
                max_length=255,
                null=True,
                verbose_name="promo code",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="promo_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Discount amount from promo code",
                max_digits=12,
                null=True,
                verbose_name="promo discount",
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("code", models.CharField(max_length=255, verbose_name="code")),
                ("discount", models.IntegerField(verbose_name="discount")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="promocodes",
                        to="course.course",
                        verbose_name="courses",
                    ),
                ),
            ],
            options={
                "verbose_name": "PromoCode",
                "verbose_name_plural": "PromoCodes",
            },
        ),
        migrations.CreateModel(
            name="UserPromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("is_used", models.BooleanField(default=True, verbose_name="is used")),
                (
                    "promocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="up_promocodes",
                        to="payment.promocode",
                        verbose_name="promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="up_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User PromoCode",
                "verbose_name_plural": "User PromoCode",
            },
        ),
    ]
