# Generated by Django 5.2.3 on 2025-10-07 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_transaction_coins_used_transaction_original_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpromocode",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction that used this promo code",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.transaction",
                verbose_name="transaction",
            ),
        ),
        migrations.CreateModel(
            name="CoinReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Amount of coins reserved", verbose_name="amount"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this reservation expires",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction that reserved these coins",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.transaction",
                        verbose_name="transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin Reservation",
                "verbose_name_plural": "Coin Reservations",
            },
        ),
        migrations.CreateModel(
            name="PromoCodeReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this reservation expires",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "promocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.promocode",
                        verbose_name="promo code",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction that reserved this promo code",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.transaction",
                        verbose_name="transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo Code Reservation",
                "verbose_name_plural": "Promo Code Reservations",
            },
        ),
    ]
